cd Comandos_GNU_e_Unix-topico_103

touch Topico_103-Introducao_da_secao.txt

touch 103.1_Trabalhando_na_Linha_de_Comando-shell_bash_echo_type_PATH.txt

touch 103.1_Trabalhando_na_Linha_de_Comando-Variaveis_de_Ambiente.txt

touch 103.1_Trabalhando_na_Linha_de_Comando-Comandos_Sequenciais_history_man.txt

touch 103.1_Trabalhando_na_Linha_de_Comando-uname_alias.txt

touch 103.1_Trabalhando_a_Linha_de_Comando-which.txt

touch 103.1_Trabalhando_na_Linha_de_Comando-Quoting.txt

touch 103.2_Aplicando_Filtros_a_Textos_e_Arquivos-cat_head_tail_sort_less_wc.txt

touch 103.2_Aplicando_Filtros_a_Textos_e_Arquivos-uniq_od_paste_split.txt

touch 103.2_Aplicando_Filtros_a_Textos_e_Arquivos-tr_cut_sed.txt

touch 103.2_Aplicando_Filtros_a_Textos_e_Arquivos-xzcat_bzcat_zcat.txt

touch 103.2_Aplicando_Filtros_a_Textos_e_Arquivos-checksums.txt

touch 103.3_Gerencimanento_Basico_de_Arquivos-cd_ls_file.txt

touch 103.3_Gerencimanento_Basico_de_Arquivos_touch_cp_mv.txt

touch 103.3_Gerencimanento_Basico_de_Arquivos_rm_mkdir_rmdir_find.txt

touch 103.3_Gerencimanento_Basico_de_Arquivos-tar_gzip_bzip2_xz.txt

touch 103.3_Gerencimanento_Basico_de_Arquivos-cpio,_dd.txt

touch 103.4_Fluxos_Pipes_e_Redirecionamentos-Redir_entrada_saida_erro_pipe.txt 

touch 103.4_Fluxos_Pipes_e_Redirecionamentos-tee_xargs_subcomandos.txt

touch 103.4_Fluxos_Pipes_e_Redirecionamentos-Outros_Redirecionadores.txt

touch 103.5_Criar_Monitorar_e_Encerrar_Processos-processos_ps_pstree_pgrep.txt

touch 103.5_Criar_Monitorar_e_Encerrar_Processos-top.txt

touch 103.5_Criar_Monitorar_e_Encerrar_Processos-kill_killall_pkill.txt

touch 103.5_Criar_Monitorar_e_Encerrar_Processos-uptime_free_screen.txt

touch 103.5_Criar_Monitorar_e_Encerrar_Processos-jobs_bg_fg_nohup.txt

touch 103.5_Criar_Monitorar_e_Encerrar_Processos-watch_tmux.txt

touch 103.6_Modificar_a_Prioridade_de_Execução_de_Processos-nice_renice.txt

touch 103.7_Pesquisar_Arquivos_de_Texto_com_Expressões_Regulares-grep_intro_regex.txt

touch 103.7_Pesquisar_Arquivos_de_Texto_com_Expressoes_Regulares-regex_sed.txt

touch 103.7_Pesquisar_Arquivos_de_Texto_com_Expressao_Regular.txt

touch 103.8_Edicao_Basica_de_Arquivos-vi-vim.txt

touch 103.8_Edicao_Basica_de_Arquivos-nano_e_emacs.txt

touch 103.8_Edicao_Basica_de_Arquivos-Definir_Editor_Padrao.txt
